# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have high level overview of PCA as well as some of the details in the algorithm itself, its time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the Data

To start, import the data stored in the file 'foodusa.csv'.

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('foodusa.csv')
df.head()

City  Bread  Burger  Milk  Oranges  Tomatoes
0    ATLANTA   24.5    94.5  73.9     80.1      41.6
1  BALTIMORE   26.5    91.0  67.5     74.6      53.3
2     BOSTON   29.7   100.8  61.4    104.0      59.6
3    BUFFALO   22.8    86.6  65.3    118.4      51.2
4    CHICAGO   26.7    86.7  62.7    105.9      51.2

## Normalize the Data

Next, normalize your data by subtracting the feature mean from each of the columns

In [7]:
df_2 = df.drop('City', axis=1)

In [10]:
df2_mean = df_2.mean()

mean_df2 = df_2 - df2_mean
mean_df2.describe()

Bread        Burger          Milk       Oranges      Tomatoes
count  2.300000e+01  2.300000e+01  2.300000e+01  2.300000e+01  2.300000e+01
mean  -9.267949e-16 -8.032222e-15  2.780385e-15  1.235726e-14 -5.869701e-15
std    2.506884e+00  7.554940e+00  6.950244e+00  1.423925e+01  7.602668e+00
min   -4.991304e+00 -1.415652e+01 -1.079565e+01 -2.839130e+01 -1.336522e+01
25%   -1.591304e+00 -4.956522e+00 -4.645652e+00 -7.591304e+00 -5.965217e+00
50%    8.695652e-03 -8.565217e-01  2.043478e-01  2.908696e+00 -1.965217e+00
75%    1.208696e+00  2.293478e+00  3.704348e+00  8.358696e+00  4.084783e+00
max    5.508696e+00  1.884348e+01  1.790435e+01  3.020870e+01  1.383478e+01

## Calculate the Covariance Matrix

The next step for PCA is to calculate to covariance matrix for your normalized data. Do so here.

In [13]:
feature_cov = np.cov([mean_df2.Bread, mean_df2.Burger, mean_df2.Milk, 
                      mean_df2.Oranges, mean_df2.Tomatoes])
feature_cov

array([[  6.2844664 ,  12.91096838,   5.71905138,   1.31037549,
          7.28513834],
       [ 12.91096838,  57.07711462,  17.50752964,  22.69187747,
         36.29478261],
       [  5.71905138,  17.50752964,  48.30588933,  -0.27503953,
         13.44347826],
       [  1.31037549,  22.69187747,  -0.27503953, 202.75628458,
         38.76241107],
       [  7.28513834,  36.29478261,  13.44347826,  38.76241107,
         57.80055336]])

## Calculate the Eigenvectors

Next, calculate the eigenvectors for your covariance matrix.

In [14]:
eig_val, eig_vec = np.linalg.eig(feature_cov)
print(eig_val)
print(eig_vec)

[218.99867893  91.72316894   3.02922934  20.81054128  37.66268981]
[[-0.02848905 -0.16532108 -0.96716354 -0.18972574  0.02135748]
 [-0.2001224  -0.63218494  0.24877074 -0.65862454  0.25420475]
 [-0.0416723  -0.44215032  0.03606094  0.10765906 -0.88874949]
 [-0.93885906  0.31435473 -0.01521357 -0.06904699 -0.12135003]
 [-0.27558389 -0.52791603 -0.03429221  0.71684022  0.36100184]]


## Sorting the Eigenvectors to Determine Primary Components

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues!

In [15]:
eig_indices = np.argsort(eig_val)[::-1]
eigvec_sort = eig_vec[:, eig_indices]
eigvec_sort

array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074],
       [-0.0416723 , -0.44215032, -0.88874949,  0.10765906,  0.03606094],
       [-0.93885906,  0.31435473, -0.12135003, -0.06904699, -0.01521357],
       [-0.27558389, -0.52791603,  0.36100184,  0.71684022, -0.03429221]])

## Reprojecting the Data

Finally, reproject the dataset using your eigenvectors. Reproject the dataset down to 2 dimensions.

In [16]:
new_data = eigvec_sort.dot(mean_df2.T).T
new_data[:5]

array([[ 11.10636706,  14.73134932, -14.17203836,   1.85530932,
        -13.15196933],
       [  1.21900301,  21.44989411,  -7.19007196,  -0.14425049,
        -18.50968283],
       [-12.29365615,  -4.73286484,  -2.84276415,  -1.4535148 ,
         -5.90817824],
       [ -4.27410508,  -4.95746329,   1.5045649 ,  -0.77897224,
         15.50821919],
       [ -2.08570219,   1.77071529,   2.26283823,  -3.2304897 ,
          4.48154292]])

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further application of PCA.