# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [9]:
# Your code here
import numpy as np
A = np.zeros((2, 2))
B = np.zeros((2, 2))
C = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        A[i,j] = np.random.randint(1, 10)
        B[i,j] = np.random.randint(1, 10)
        C[i,j] = np.random.randint(1, 10)
# A = np.array([[1, 2], [3, 4]])
# B = np.array([[4, 3], [2, 1]])
# C = np.array([[1, 2], [3, 4]])

A.dot((B+C)) == A.dot(B) + A.dot(C)

array([[ True,  True],
       [ True,  True]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [11]:
# Your code here 
A.dot(B.dot(C)) == (A.dot(B)).dot(C)

array([[ True,  True],
       [ True,  True]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [12]:
# Your code here 
A.dot(B) == B.dot(A)

array([[False, False],
       [False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [14]:
# Your code here 
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x.transpose().dot(y) == y.transpose().dot(x)

True

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [15]:
# Your code here 
(A.dot(B)).transpose() == B.transpose().dot(A.transpose())

array([[ True,  True],
       [ True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 